services:
  - type: web
    name: assignment
    env: node
    buildCommand: cd api && npm install && cd .. && cd client && npm install && npm run build && cd ..
    startCommand: node api/server.js
    envVars:
      - key: NODE_ENV
        value: production