services:
  - type: web
    name: my-app-backend
    env: node
    buildCommand: cd api && npm install
    startCommand: node api/server.js
    envVars:
      - key: NODE_ENV
        value: production